/**
 * EMS tags for wallbox battery settings not yet exposed in easy-rscp EMSTag enum.
 * Source: rscp2mqtt RscpTags.h
 */
export const EMS_REQ_SET_WB_DISCHARGE_BAT_UNTIL = '0100027C'
export const EMS_SET_WB_DISCHARGE_BAT_UNTIL = '0180027C'
export const EMS_REQ_GET_WB_DISCHARGE_BAT_UNTIL = '0100027D'
export const EMS_GET_WB_DISCHARGE_BAT_UNTIL = '0180027D'

export const EMS_REQ_SET_WALLBOX_ENFORCE_POWER_ASSIGNMENT = '0100027A'
export const EMS_SET_WALLBOX_ENFORCE_POWER_ASSIGNMENT = '0180027A'
export const EMS_REQ_GET_WALLBOX_ENFORCE_POWER_ASSIGNMENT = '0100027B'
export const EMS_GET_WALLBOX_ENFORCE_POWER_ASSIGNMENT = '0180027B'